from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

informations = """
   Robert Baden-Powell, titolo completo Lord Robert Stephenson Smyth Baden-Powell, primo Barone Baden-Powell di Gilwell (['beɪdən 'paʊəl]; Londra, 22 febbraio 1857 – Nyeri, 8 gennaio 1941), è stato un generale, educatore e scrittore britannico, noto soprattutto per essere stato il fondatore, nel 1907, del movimento mondiale dello scautismo e subito dopo di quello del guidismo.

Per i meriti riconosciutigli dalla fondazione del movimento scout, oltre ad altre onorificenze, gli furono conferiti i titoli dapprima di cavaliere commendatore dell'Ordine del Bagno (Sir), poi di baronetto (Sir) e infine di barone (Lord). Gli scout e le guide lo chiamano più semplicemente B.-P. (come soleva abbreviare la sua firma). Il giorno della nascita sua e di sua moglie Olave, il 22 febbraio, è festeggiato con il nome di Thinking Day (Giornata del Pensiero) durante il quale gli scout sono soliti donare una somma (solitamente pari ad un euro, un dollaro, ecc.) ad una causa scelta da ogni gruppo scout.
Biografia
Infanzia

Nacque a Londra, in Stanhope Street, appena a nord di Hyde Park, il 22 febbraio 1857, venendo battezzato con il nome di Robert Stephenson Smyth Powell. Fin dai primissimi anni di vita venne chiamato Stephe (ˈstɪiˑvjə), Ste o Stephenson. Divenne noto come Robert solo dopo l'assunzione del cavalierato, scegliendo di essere Sir Robert. Fu il sesto degli otto figli del reverendo Baden Powell (Baden era il nome, Powell il cognome), Savilian Professor of Geometry a Oxford e di Henrietta Grace Smyth. Il professor Powell aveva comunque già avuto altri quattro figli dal secondo dei suoi due precedenti matrimoni.

Perse il padre all'età di soli tre anni e fu cresciuto dalla madre, figlia dell'ammiraglio britannico William Henry Smyth, una donna fortemente determinata a far sì che i suoi figli avessero successo nella vita. Il suo bisnonno, Joseph Brewer Palmer Smyth, si dice fosse emigrato in America come colonizzatore del New Jersey e che, a causa della sua lealtà alla corona britannica, fosse stato costretto a fuggire dagli Stati Uniti, perdendo tutti i suoi possedimenti.

Henrietta Grace temette sempre che questa storia potesse mascherare qualche amara verità. Solo nel 1892, George Baden-Powell, fratello di Robert, appena eletto al Parlamento, aspettandosi una nomina a cavaliere o a pari d'Inghilterra, ricostruì il proprio albero genealogico, scoprendo che Joseph Smyth era un truffatore e un bigamo e probabilmente non il nonno di Henrietta. Joseph Smyth non era mai tornato in Inghilterra dove l'attendeva una condanna per frode. La sua richiesta di risarcimento per aver perso tutte le sue proprietà era stata sempre bocciata dal Ministero del Tesoro perché i documenti d'appoggio erano stati dichiarati contraffatti. Non fu mai trovato neppure il certificato di matrimonio tra lui e quella che avrebbe dovuto essere la madre dell'ammiraglio Smyth. Di fatto, egli morì o scomparve in America nel 1789 per una probabile patologia renale.

L'ammiraglio Smyth, padre di Henrietta Grace, fu un uomo che si fece da solo, iniziando la carriera come mozzo; pertanto avrebbe anche potuto andare orgoglioso della propria vita, ma non fu da meno del padre; si appropriò dello stemma del capitano John Smith, fondatore della Virginia (noto per esser stato salvato al palo della tortura dalla nativa americana Pocahontas) ed Henrietta proseguì la strada aperta dai suoi avi, nel suo sforzo continuo di procurare a sé stessa e ai figli un background nobiliare, arrivando ad affermare che lei fosse la pronipote dell'ammiraglio Horatio Nelson. In realtà, il fratellastro della madre di Henrietta aveva sposato una lontanissima parente di Nelson. Henrietta arrivò anche a dire che suo padre era stato a Napoli con Nelson quando quest'ultimo era già morto da anni.

I figli di Henrietta presero sempre sul serio queste storie, almeno fino alla scoperta fatta da George Baden-Powell nel 1892. Quando Robert ebbe 12 anni, Henrietta, con l'intento di fornire, anche nel cognome, un sostegno al futuro dei figli, cambiò il cognome di famiglia da Powell in Baden-Powell, sfruttando la "classe" che il doppio cognome comportava in certi ambienti e usando come primo cognome il tedesco Baden, in un periodo in cui tutto ciò che si avvicinava al germanismo della famiglia reale comportava vantaggi sociali.

Robert ebbe la sua prima educazione in casa, insieme ai fratelli minori Agnes e Baden. Ricevevano lezioni di lettura, scrittura e canto sia da Henrietta che dalla governante tedesca, Fräulein Groffel. All'età di sette anni Robert fu mandato in una scuola privata gestita da una maestra nella propria casa in Kensington Square. All'età di 11 anni, "Stephe" (come si faceva chiamare all'epoca) fu inviato alla Rose Hill, la scuola preparatoria di Tunbridge Wells, dove anche suo padre era stato educato.

Successivamente Henrietta, che aveva mandato due dei suoi figli, George e Frank, al Marlborough College, optò per Robert e Baden per Charterhouse, probabilmente per ragioni economiche, sperando che entrambi potessero usufruire della borsa di studio "Gownboy" che consentiva a 60 ragazzi di frequentare gratis. Queste borse di studio venivano assegnate a ragazzi poveri di buona famiglia e questi ragazzi non si sentivano affatto inferiori a quelli i cui genitori pagavano una sostanziosa retta. Charterhouse si trovava allora a sud di Londra, ma si sarebbe poi trasferita a Godalming, nel Surrey, in aperta campagna. Qui visse insieme agli altri 59 "Gownboys" nello stesso edificio, dove la disciplina veniva gestita in proprio, nel senso che gli studenti degli ultimi anni ne erano responsabili e gestivano spesso tramite atti di "nonnismo" che comprendevano frequenti punizioni corporali.

Baden-Powell sperimentò le sue tecniche di scouting nel "Copse" ("La Macchia"), un boschetto appena al di fuori di Charterhouse, peraltro già provate con i fratelli maggiori nelle loro scorribande sia a bordo del battello di famiglia Koh-I-Noor nella Manica sia nell'entroterra inglese. A Charterhouse non si distinse per lo studio, ma d'altronde, nella Gran Bretagna dell'epoca vittoriana, la scuola non aveva lo scopo di dare cultura, anche se ciò potrebbe suonare strano, ma quello di formare il carattere, attraverso la vita in comune e privilegiando il teatro e soprattutto lo sport. Stephe non perse occasione per mettersi in mostra, recitando e giocando a cricket e a calcio. Si distinse nel primo, meno nel secondo: era un buon portiere, anche se era più famoso tra i suoi compagni più per le scenette che per le parate. Aveva inoltre un'inclinazione per la musica e le sue doti di disegnatore lo misero in grado più tardi di illustrare da sé i suoi libri.

A Charterhouse, Baden-Powell non fece amicizie strette; era timido e insicuro e la sua "verve" e le sue battute sarcastiche servivano a evitare che divenisse lui stesso oggetto di scherno. Attaccava prima di essere attaccato: una regola che metterà in pratica anche più avanti nella vita.

Le sue prime esperienze di tecniche scout furono il cacciare e cucinare animali - e l'evitare i professori - nei boschi limitrofi, rigidamente vietati agli studenti. Ambidestro, suonò anche il pianoforte e il violino con un certo talento, anche se non si separò mai dalla sua ocarina che lo accompagnò sempre. Si divertì anche a recitare. Le vacanze generalmente le passò facendo spedizioni in barca o in canoa con i suoi fratelli.
Carriera militare
India

A 19 anni prese il diploma a Charterhouse; tentò di entrare a Oxford, ma la sua scarsa preparazione non gli consentì di superare gli esami di ammissione. Partecipò con scarsa convinzione a un concorso per entrare in cavalleria e in fanteria, giungendo secondo nella graduatoria per la prima e quinto per la seconda, e optò per la più nobile cavalleria, nel reggimento che aveva formato l'ala sinistra dello schieramento della cavalleria nella famosa "Carica della brigata leggera" nella guerra di Crimea: il 13° Ussari della Guardia.

La scelta della cavalleria non fu facile; lo stipendio era piuttosto basso e i costi eccessivi, costi che nel caso di Baden-Powell avrebbero dovuto essere sostenuti con l'apporto del salvadanaio di famiglia. Per lo stesso motivo, Baden-Powell non sarebbe mai potuto rimanere in Inghilterra, dove il costo della vita rispetto all'India sarebbe stato proibitivo. Certamente la scelta dell'India e del 13° Ussari non furono casuali, visto che la madre aveva brigato parecchio l'anno prima con uno dei colonnelli comandanti del 13° per mandarcelo.

Il 30 ottobre 1876, dopo un terribile viaggio in nave di cinque settimane, Baden-Powell raggiunse il porto di Bombay. Durante il viaggio ebbe modo di mettersi in mostra, aiutando i commilitoni a organizzare delle recite, i cui copioni si era portato dietro. Da Bombay raggiunse la sua destinazione a Lucknow (nell'Uttar Pradesh), un posto orribile che gli fece rimpiangere di aver raggiunto l'India già alla fine della terza settimana. Leggende metropolitane vogliono che Baden-Powell vivesse l'esperienza di Lucknow disinvoltamente. In realtà, nei primi due anni trascorsi in India tempestò di lettere la madre e il fratello George perché gli trovassero una sistemazione nella "Home Guard", in Inghilterra. La famiglia non fece nemmeno il tentativo; come George aveva spiegato alla madre, il mantenimento di Stephe in Inghilterra (che peraltro sarebbe ricaduto sulle sue spalle e su quelle dell'altro fratello Frank) sarebbe stato impossibile da sostenere.

Gli esercizi militari a Lucknow erano pesanti e gli istruttori sfioravano il sadismo. Ma l'incubo peggiore era il clima: nei primi due anni in India il 13° Ussari non venne coinvolto nemmeno in una scaramuccia, ma colera e tifo decimavano tutti. Il caldo era insopportabile: le attività iniziavano alle 4:30 del mattino e dopo le 8 diveniva impossibile muoversi all'aperto. Baden-Powell iniziò a soffrire fisicamente. Le uniche note positive furono il superamento nel 1878 di un corso di otto mesi. Questo gli consentì di ottenere l'ambita stella, unico in tutta l'India, il che gli fece assegnare il grado di tenente (con retroattività di due anni) e la visita a Simla al fratellastro Baden Henry (che Baden-Powell detestava, ma senza le cui donazioni in denaro non avrebbe mai potuto sopravvivere).

A Simla Baden-Powell, dal carattere molto più aperto del fratellastro, ebbe modo di conoscere tutti i notabili militari e si mise in vista recitando in diverse commedie. Alla fine dei suoi due anni la commissione medica militare dichiarò le sue condizioni fisiche assolutamente inadatte al proseguimento del servizio a Lucknow e lo spedì a casa a spese dello Stato per un anno.
Intermezzo inglese

Tornato in Inghilterra, Baden-Powell trovò una nuova casa più grande: una stanza per ciascuno dei figli e un salone per le feste che Henrietta organizzava spesso. In poco tempo, le cure della madre e della sorella fecero effetto e Baden-Powell si riprese. Fu un continuo girare da un parente all'altro e un portare ai parenti dei suoi commilitoni rimasti a Lucknow i loro saluti. Una cena dopo l'altra, quindi, ma anche molto teatro. Dopo pochi giorni, infatti, Baden-Powell aveva rimosso i ricordi negativi e cominciò a provare nostalgia per le cose buone. Era determinato, dunque, a fare incetta di copioni di commedie e musical da poter rappresentare una volta tornato. Non che lo volesse: fece di tutto per rimanere, ma si scontrò ancora una volta contro il portafoglio della famiglia. Frequentò un corso di armi leggere a Hythe e lo superò brillantemente, acquisendo il diritto di divenire a sua volta istruttore del proprio reggimento, cosa che gli procurò altre 100 rupie al mese (oltre le miserevoli 10 sterline del suo stipendio). Il tempo volò e, poco meno di due anni dopo la sua partenza, fece rientro a Lucknow. Era l'ottobre del 1880 e Stephe aveva ora 23 anni. Durante la sua assenza c'era stata una rivolta in Afghanistan, domata con perdite dal generale Roberts.
Di nuovo in India

Giunto a Lucknow scoprì che il suo reggimento era ancora a Kandahar. Per cercare di contenere gli effetti della Jihād scatenata contro gli inglesi, le impiccagioni e le fustigazioni si susseguivano senza sosta. A completare l'opera, verso la quale solo apparentemente Baden-Powell sembrava indifferente, il comandante lo inviò a perlustrare il campo di battaglia di Maiwand, dove centinaia di inglesi e afgani, senza contare le bestie, erano caduti combattendo e i cui corpi, ora, venivano divorati dagli animali. Stephe restò scosso, ma apprezzò il fatto di poter far pratica di ricognizione. Intanto, per combattere la noia quotidiana, tirò fuori i copioni teatrali che s'era portato dietro e organizzò delle recite. L'unica nota stonata di questo periodo fu che l'unico colpo d'arma da fuoco sparato da Stephe fu contro la propria gamba, cosa che lo costrinse a letto per circa due mesi.

A Quetta, dove il reggimento si era trasferito, incontrò per la prima volta quello che sarebbe stato l'unico vero amico che Baden-Powell mai ebbe, il tenente Kenneth McLaren che, a causa del suo aspetto adolescenziale, Stephe chiamò "The Boy". L'amicizia con McLaren iniziò il giorno in cui Baden-Powell si trovò a dover consolare l'amico per la perdita della madre. Visti gli strettissimi rapporti che Stephe aveva con Henrietta, non meraviglia che Baden-Powell si immedesimasse nella situazione dell'amico. Da quel giorno i due amici divisero ogni cosa: avevano bungalow sempre vicini, condividevano i cavalli da polo (McLaren era in questa specialità un vero fuoriclasse), i cani e gli hobby. Tra questi spiccava il pigsticking, una sorta di caccia al cinghiale, a cavallo e con una lancia relativamente corta. Sport pericoloso («Il cinghiale selvatico è definito il solo animale che osi bere alla stessa pozza d'acqua della tigre»[1]) che, tra l'altro, prevedeva spesso il dover stanare a piedi l'animale, cosa che Baden-Powell e McLaren facevano da soli, rischiando, quando i battitori fallivano.

L'amicizia tra The Boy e Stephe mise in crisi i rapporti con la famiglia, dato che Baden-Powell, ogni qualvolta riusciva a ottenere una licenza, non tornava più in Inghilterra. Henrietta non apprezzò mai questa amicizia: mentre infatti aveva indottrinato efficacemente i figli contro il pericolo delle donne, non aveva pensato che l'amicizia maschile avrebbe potuto sostituirla.

Tra il 1892 e il 1893, come responsabile dell'Intelligence britannica nel Mediterraneo, fu spesso in giro, non di rado in abiti borghesi, lungo le coste del Mediterraneo allo scopo di raccogliere informazioni militari; fu in questo periodo che si trovò anche sulle alture dello Stretto di Messina, disegnando schizzi dei Forti Umbertini in fase di costruzione che tutt'oggi punteggiano le due coste dello Stretto. Nel 1895 ebbe un incarico speciale in Africa e ritornò in India nel 1897 al comando del quinto reggimento Dragoon Guards. Incrementò e perfezionò le sue doti di esploratore grazie alla conoscenza della popolazione Zulu, all'inizio degli anni ottanta, nella provincia KwaZulu, in Sudafrica, dove il suo reggimento fu di stanza e dove fu menzionato in diversi rapporti. Le sue capacità impressionarono i suoi superiori e presto venne trasferito ai Servizi segreti britannici. Viaggiò spesso travestito da collezionista di farfalle, nascondendo documenti militari nei suoi disegni di farfalle.

In seguito divenne un ufficiale dell'intelligence inglese nella base di Malta nel Mediterraneo. Tra il 1887 e il 1888 condusse poi una campagna coronata da successo contro l'Impero ashanti in Africa e fu promosso al comando del quinto reggimento Dragoons nel 1897. Qualche anno dopo scrisse un piccolo manuale, intitolato Aids to Scouting for NCO's and Men (Suggerimenti per l'esplorazione per sottufficiali e soldati), un compendio di letture utili all'addestramento delle reclute all'esplorazione. Utilizzando questo e altri metodi fu in grado di addestrarle a pensare indipendentemente, usare il loro spirito di iniziativa e a sopravvivere in ambienti selvaggi. Gli indigeni lo temevano, tanto che gli assegnarono il nome di Impeesa, il lupo che non dorme mai, per il suo coraggio, la sua bravura di esploratore e la sorprendente abilità nel seguire le tracce.
La guerra in Sudafrica
Lo stesso argomento in dettaglio: Assedio di Mafeking.
Robert Baden-Powell in Sudafrica nel 1896

Ritornò in Sudafrica prima della Seconda guerra boera e fu coinvolto in numerose azioni contro gli Zulu. Fu promosso, divenne il più giovane colonnello dell'esercito britannico e divenne responsabile dell'organizzazione di forze di frontiera che dovevano assistere l'esercito regolare. Nell'assolvimento di questo incarico, fu bloccato nell'assedio di Mafeking (città allora importante per essere uno snodo ferroviario e sorta su un lieve rialzo nella sterminata pianura sudafricana verso il Botswana, il cui nome significava "luogo delle pietre"; oggi è chiamata Mahikeng) e circondato dall'esercito Boero, in vantaggio per numero di qualche migliaio di unità. Nonostante l'inferiorità numerica, la sua guarnigione resse l'assedio da parte dei Boeri per 217 giorni, grazie anche a particolari tecniche utilizzate da Baden-Powell: furono realizzati falsi campi minati e i suoi soldati furono istruiti a simulare di dover evitare inesistenti recinzioni di filo spinato.

Compì la maggior parte dei lavori di esplorazione di queste aree e istruì, con la collaborazione determinante del maggiore Lord Edward Cecil, un gruppo di ragazzi del luogo al ruolo di vedette e portaordini e insegnò loro come oltrepassare le linee nemiche. Uno solo dei ragazzi che facevano parte dei "Cadetti di Mafeking", Frankie Brown di 9 anni, perse la vita, a seguito delle ferite riportate dallo scoppio di una granata boera. Baden-Powell fu molto impressionato dal coraggio e dalla generosità con le quali i ragazzi attendevano ai loro compiti. L'assedio terminò con la liberazione di Mafeking il 16 maggio del 1900. Promosso maggior generale, divenne un eroe nazionale.

La Gran Bretagna aveva trattenuto il respiro per tutti quei lunghi mesi e quando finalmente giunse la notizia «Mafeking è stata liberata», impazzì letteralmente di gioia. Aprendo il dizionario inglese si può trovare il verbo to maffick ("celebrare con stravaganti manifestazioni pubbliche") e la parola maffication ("celebrazione tumultuosa"), termini nati in quei giorni di entusiasmo. Dopo aver organizzato un servizio di polizia nazionale in Sudafrica, ritornò in Inghilterra nel 1903, assumendo l'incarico di ispettore generale della cavalleria.
Ritorno in Inghilterra
Lo stesso argomento in dettaglio: Campo di Brownsea Island.
La pietra che ricorda il primo campo scout

Al suo ritorno, Baden-Powell scoprì che il suo manuale d'addestramento Aids to Scouting aveva avuto un grande successo e che era stato adottato da insegnanti e da associazioni giovanili. Avendo seguito conferenze dello scozzese Sir William Alexander Smith, che aveva fondato a Glasgow il 4 ottobre 1883 le Boys' Brigades e dell'altro scozzese naturalizzato canadese, Ernest Thompson Seton, fondatore dei cosiddetti "Woodcraft Indians" già nel 1902, Baden-Powell accettò incarichi in questa organizzazione interconfessionale cristiana, che campeggiava dal luglio 1886. A seguito di ciò, Baden-Powell decise di riscrivere Aids to Scouting per un pubblico più giovane e nell'agosto 1907 tenne un campo sull'isola di Brownsea con venti ragazzi di diverse estrazioni sociali, per verificare la praticabilità di alcune delle sue idee. Scautismo per ragazzi fu in seguito pubblicato, nel marzo 1908, in sei fascicoli. Ragazzi e ragazze si unirono spontaneamente per formare squadriglie ed il movimento scout divenne inaspettatamente un fenomeno di massa, dapprima nazionale, in seguito internazionale.

Il movimento scout crebbe in parallelo ed in amicizia alle Boy's Brigades. Durante una competizione fra tutti gli scout, tenutasi a Crystal Palace, Londra, nel settembre 1909, B.-P. venne a sapere dell'esistenza delle prime Girl Scouts. Piuttosto che accogliere le ragazze nell'associazione dei Boy Scout, preferì fondare nel 1910 il movimento parallelo del guidismo, sotto il coordinamento della sorella Agnes.

Nonostante, secondo alcuni, potesse ambire a diventare generale, Baden-Powell decise di ritirarsi dall'esercito nel 1910, seguendo il consiglio di Edoardo VII, che gli suggerì che avrebbe potuto rendere un servizio migliore al suo paese promuovendo lo scautismo. In occasione dell'incoronazione di Giorgio V, Baden-Powell conobbe Nogi Maresuke[2]. Al ritorno in patria Nogi contribuì in maniera determinante alla diffusione dello scautismo in Giappone.

Nel gennaio 1912 B.-P. incontrò Olave Soames, in seguito sua moglie, mentre sul transatlantico Arcadian era diretto a New York per uno dei suoi tour mondiali. Lei era una ragazza di 23 anni, lui ne aveva 55 e condividevano la stessa data di nascita, il 22 febbraio. Si fidanzarono nel settembre dello stesso anno e la loro liaison divenne un evento mediatico. Per evitare l'intrusione della stampa, si sposarono in segreto il 30 ottobre 1912. Ogni scout ed ogni guida d'Inghilterra e del mondo donò un penny per contribuire a comperare un regalo di nozze, un'automobile.
Dalla prima guerra mondiale in poi

Allo scoppio della prima guerra mondiale, nel 1914, Baden-Powell si mise a disposizione dell'esercito. Non gli fu però assegnato nessun incarico ed in proposito Lord Kitchener commentò: «Posso trovare facilmente numerosi generali di divisione altrettanto competenti, ma non troverei nessuno che possa continuare il suo inestimabile lavoro nei Boy Scout». Fu detto che Baden-Powell fosse in realtà attivo nello spionaggio e gli organi dell'intelligence operarono perché questa vera o presunta notizia si diffondesse.

Nel 1920, esattamente 13 anni dopo il primo campo, si tenne ad Olympia, Londra, il primo jamboree mondiale, cioè un grande raduno di scout. Nella cerimonia di chiusura B.-P. fu acclamato all'unanimità Capo Scout del Mondo. B.-P. fu nominato baronetto nel 1922, diventando Sir Robert Baden-Powell.

Sotto la sua guida il movimento scout internazionale crebbe. Nel 1922 c'erano più di un milione di scout in 32 paesi; nel 1939 erano più di 3,3 milioni.

Nel 1929, durante il terzo jamboree mondiale, ricevette un regalo comprato con le offerte (un penny) di tutti gli scout del mondo. Il regalo fu un'auto nuova, una Rolls-Royce, che fu prontamente ribattezzata Jam-Roll e anche una roulotte, che fu battezzata Eccles Cake e che in seguito fu usata nei suoi numerosi viaggi per diffondere lo scautismo. Nel corso dello stesso jamboree fu creato Pari del Regno Unito e scelse il titolo di Barone Baden-Powell of Gilwell. Non avendo possedimenti o tenute, scelse come luogo da indicare nel titolo Gilwell Park, il primo centro internazionale di formazione di capi scout, aperto nel 1919 nella contea dell'Essex.

Gli fu conferita una menzione d'onore nel 1937 e ricevette 28 decorazioni da altri stati.
La famiglia cresce

I Baden-Powell ebbero tre figli, un maschio e due femmine, che ebbero il titolo di cortesia di "onorevole" (Honourable) nel 1929, quando Baden-Powell divenne Lord; il primo figlio successe al padre nel 1941:

    Peter, che divenne poi il secondo Barone Baden-Powell (1913-1962), ebbe due figli ed una figlia
    Heather Baden-Powell (1915-1986), ebbe due figli
    Betty Baden-Powell (1917-2004), che sposò nel 1936 Gervas Charles Robert Clay (1907-2009) ed ebbe tre figli e una figlia

Molti dei nipoti sono tuttora attivi nello scautismo o nel guidismo.
Gli ultimi anni
La tomba di Robert Baden-Powell

«...ma il vero modo di essere felici è quello di procurare la felicità agli altri. Procurate di lasciare questo mondo un po' migliore di quanto non l'avete trovato e, quando suonerà la vostra ora di morire, potrete morire felici nella coscienza di non aver sprecato il vostro tempo, ma di aver fatto "del vostro meglio".»

(Dall'Ultimo Messaggio di B.-P.)

Poco dopo il matrimonio, Baden-Powell cominciò ad avere problemi di salute, patendo diverse malattie. Si lamentava di continui mal di testa, che furono considerati dal suo dottore come psicosomatici e trattati attraverso l'analisi dei sogni. I mal di testa peggiorarono e lo portarono a smettere di dormire con Olave e a spostarsi in una camera da letto allestita sul suo balcone. Nel 1934 gli fu asportata la prostata e, per riprendersi, nel 1939 traslocò in una casa che aveva commissionato in Kenya, paese che aveva visitato in precedenza.

Nel 1938 l'Accademia di Svezia propose Baden-Powell e il movimento scout come destinatari del Premio Nobel per la pace, per l'impegno profuso per la stessa, per l'anno 1939 (dopo essere stato nominato più volte negli anni precedenti, tra cui 10 nomination nel 1928)[3]. Lo scoppio della seconda guerra mondiale fece decidere all'accademia di Svezia di non assegnare il premio per l'anno 1939 e successivi.

Deluso dalla fine della pace in Europa, Baden-Powell morì in Kenya, a Nyeri, vicino al Monte Kenya, l'8 gennaio del 1941. Sulla sua tomba è riportato il segnale di pista "Sono tornato a casa" ().
Dopo la sua morte

Dopo la morte di Powell il movimento scout continuò e continua a crescere, fino a riunire oggi oltre 28 milioni di scout (ragazzi e ragazze), parallelamente a 12 milioni di guide. Oltre all'Organizzazione Mondiale del Movimento Scout (OMMS) ed all'Associazione Mondiale Guide ed Esploratrici (AMGE), le uniche da lui fondate direttamente, esistono numerosissime altre associazioni che si ispirano più o meno fedelmente al suo metodo.

Gli scout e le guide hanno scelto la ricorrenza del 22 febbraio, la data di nascita sia di Powell sia di sua moglie Olave, come momento di festa per ricordare e celebrare il lavoro del Capo Scout e della Capo Guida del mondo. Le associazioni scout solitamente chiamano la data "Founder's Day", mentre le guide usano l'espressione "Thinking Day" (o, più propriamente, World Thinking Day). In particolare, le associazioni di Guide dedicano questa giornata a conoscere meglio la dimensione internazionale del movimento ed ogni anno si segue un tema indicato dall'AMGE. In Italia si usano di solito sia l'espressione inglese "Thinking Day", sia espressioni più o meno equivalenti come "Giornata del pensiero" o "Giornata del ricordo".
Baden-Powell nei media
Cinema

Nel 1958 il celebre regista Cecil B. DeMille cominciò a lavorare ad un film sulla vita del generale inglese, che sarebbe stato interpretato da David Niven, ma nel gennaio del 1959 il regista morì e il progetto venne abbandonato. Nel film Aquile randagie (2019) di Gianni Aureli, Baden-Powell è interpretato da Marc Fiorini.
Televisione

Baden-Powell è stato interpretato in alcune serie televisive inglesi e statunitensi:

    Nella serie TV Hallmark Hall of Fame (1951) è interpretato da Basil Howes nell'episodio Juliette Low and the Girl Scouts (trasmesso il 9 marzo 1952).
    Nella miniserie di 8 episodi The Edwardians (1972) è interpretato da Ron Moody (da adulto) e Jasper Jacob (da ragazzo).

Fumetti

A settembre 1989 è uscito in Francia il primo volume a fumetti Baden-Powell con la storia di Baden-Powell inclusa la nascita dello Scautismo realizzato da Serge Saint Michel con la partecipazione dell'allora Segretario Generale dell'Organizzazione Mondiale dello Scautismo Laszlo Nagy e disegni di Bernard Dufossé; la versione italiana ha una introduzione dell'allora presidente della Federazione Italiana dello Scautismo Claudio Aicardi e in calce foto dell'AGESCI e del CNGEI.

Nell'agosto 2007 è uscito il volume a fumetti Impeesa - La grande avventura di Baden Powell edito dalla Lizard Edizioni; il volume, scritto da Paolo Fizzarotti (direttore della rivista ufficiale del CNGEI Scautismo) e disegnato da Ivo Milazzo, con la prefazione di Eduardo Missoni, all'epoca segretario generale dell'Organizzazione Mondiale del Movimento Scout, racconta la storia di Baden-Powell prima della fondazione dello scautismo.
"""

if __name__=="__main__":
    print("Pippo")
    summary_template=(f"date le informazioni {informations} voglio creare: "
                      f"1. un piccolo summary"
                      f"2. fatti interessanti che la riguardano")

    summary_prompt_template=PromptTemplate(input_variables="informations", template=summary_template)
    llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo")
    chain = summary_prompt_template | llm
    response = chain.invoke(input={"informations":informations})
